import PixelTrail from "@/components/ui/pixel-trail"
import { ThemeProvider } from "@/components/ui/theme-provider"
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"

const geistSans = Geist({
  variable: "--font-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={geistSans.variable} suppressHydrationWarning>
      <body
        className={`${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="fixed inset-0 z-0">
            <PixelTrail
              pixelSize={25}
              delay={0}
              fadeDuration={1000}
              pixelClassName="bg-card-foreground/50"
            />
          </div>
          <main className="animate-in fade-in relative z-10 mx-auto flex w-full flex-col gap-6 p-5 duration-1000 ease-out md:max-w-3xl">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
